config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get :dashboard, to: 'pages#dashboard' # As a user I can access my dashboard

  resources :groups do # Full CRUD
    resources :events, only: [:new, :create] # As a user I can create an event for a certain group via a form
    resources :messages, only: [:create] # As a user I can send messages within the group page
    resources :group_memberships, only: [:new, :create] # As a user I can send invites to join the group
  end

  resources :events, only: [:index, :show, :edit, :update, :destroy] do # As a user I can do the rest of the crud inside the event page
    post 'votes', to: 'votes#bulk_create', as: 'votes'
    post 'full', to: 'events#full', as: 'full'
    post 'booked', to: 'events#booked', as: 'booked'
  end

  resources :event_memberships, only: [:update] # As a user I can declare that I won't be coming for this event

  resources :group_memberships, only: [:destroy] # As a user I can leave a group

  resources :notifications, only: [:index] # As a user I can see all my notifications

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_memberships, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :events, dependent: :destroy

  has_many :users, through: :group_memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = current_user.groups
  end

  def show
    @messages = @group.messages.order(created_at: :asc)
    @message = Message.new
    @users = @group.users
    @events = @group.events
    @group_membership = GroupMembership.new
    @all_users = User.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    # Set current user as Owner of the group
    @group.owner_id = current_user

     if @group.save
      # Invite the owner
      invite_group_owner(@group)
      # And redirects
      redirect_to group_path(@group)
    else
      puts "- ERROR : failed to create group :"
      p @group
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      puts "- ERROR : failed to update group :"
      p @group
      render "edit"
    end
  end

  def destroy
    @group.destroy
    redirect_to dashboard_path
  end

private
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:title, :avatar_file)
  end

  def invite_group_owner(group)
    @group_membership = GroupMembership.new
    @group_membership.user = current_user
    @group_membership.group = @group
    @group_membership.save
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="d-flex flex-column form-inputs my-3 bw_form-inputs-no-border justify-content-center text-center">
    <%= f.input :title, label:'Group name :', placeholder: 'Type in the group name',
                required: true,
                autofocus: true %>
    <%= f.input :avatar_file, :as => :hidden,
                required: true, input_html: { id: 'avatar' } %>

    <label class="string required">Choose your avatar: *</label>
    <div class="mt-3 avatars-container row row-cols-3">
      <% @avatars = Avatar.get_group_avatars %>
        <% @avatars.each do |avatar| %>
          <div class="avatars col" data-avatar=<%= "avatars/groups/#{avatar}.svg" %>>
            <%= show_svg("avatars/groups/#{avatar}.svg") %>
          </div>
        <% end %>
    </div>
    <%= f.button :submit, class: 'btn btn-primary w-100 fixed-bottom btn-lg rounded-0' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% @page_title = @group.title %>
<% @back_button = "back" %>
<% @cog_button = "group" %>

<%= render 'shared/navbar' %>
<div class="container col-10 col-lg-4 d-flex flex-column justify-content-center my-5">
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<% @page_title = "Groups" %>
<% @back_button = "logout" %>
<% @cog_button = "user" %>

<%= render "shared/navbar"  %>

<div class="container d-flex flex-column justify-content-center mt-2 bw_padding-bottom-1">

    <% @groups.each do |group| %>

    <div class="bw_group d-flex flex-row justify-content-left align-items-center py-3 px-0 pr-3">
      <div class="col-2 pl-0">
        <%= show_svg(group.avatar_file) %>
      </div>

      <div class="flex-grow-1 justify-content-between d-flex flex-row align-items-center">
        <strong class="text-dark"><%= link_to group.title, group_path(group) %></strong>
        <small class="text-muted"><i class="fas fa-user-friends"></i> <%= group.group_memberships.count %></small>
      </div>
    </div>

    <% end %>

    <div class="bw_group d-flex flex-row justify-content-left align-items-center py-3 px-0">
      <div class="col-2 pl-0">
        <%= show_svg("avatars/plus.svg") %>
      </div>
      <strong class="text-dark"><%= link_to "Add a new group", new_group_path %></strong>
    </div>
  </div>

<%= render "shared/bottombar"  %>

app/views/groups/new.html.erb
<% @page_title = "New group" %>
<% @back_button = "back" %>
<% @cog_button = "user" %>

<%= render 'shared/navbar' %>
<div class="container col-10 col-lg-4 d-flex flex-column justify-content-center my-5">
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<% @page_title = @group.title %>
<% @back_button = "back" %>
<% @cog_button = "group" %>
<% @show_bolt_button = true %>

<%= render 'shared/navbar' %>

<div class="container bw_auto-h-100 d-flex flex-column justify-content-between">
  <div class="d-flex flex-column justify-content-center align-items-start mt-4">
    <h2>🎂<%= @events.count %> Events</h2>
    <div class="bw_carrousel">
      <ul class="list-inline">
        <li class="list-inline-item"><%= link_to new_group_event_path(@group) do %><div class="avatar"><%= show_svg("avatars/plus.svg") %></div><% end %></li>
        <% @events.each do |event| %>
        <li class="list-inline-item"><%= link_to event_path(event) do %><div class="avatar"><%= show_svg(event.avatar_file) %></div><% end %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="d-flex flex-column justify-content-center align-items-start mt-2">
    <h2>👨‍👨‍👦‍👦<%= @users.count %> Members</h2>
    <div class="bw_carrousel">
      <ul class="list-inline">
        <li class="list-inline-item"><%= link_to new_group_group_membership_path(@group) do %><div class="avatar"><%= show_svg("avatars/plus.svg") %></div><% end %></li>
        <% @users.each do |user| %>
        <li class="list-inline-item"><div class="avatar"><%= show_svg(user.avatar_file) %></div></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="chat mt-2">
    <h2>💌 Messages</h2>
    <% if @messages %>
      <div class="messages border-top border-bottom border-primary" id="messages">
        <% @messages.each do |message| %>
          <div class="message mb-4">
            <strong><%= message.user.nickname %></strong><small> on <%= message.created_at.strftime('%b %d at %R') %></small>
            <p><%= message.content %></p>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= render "messages/new", group: @group, message: @message %>
  </div>
</div>
<%= render 'shared/bottombar' %>