config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get :dashboard, to: 'pages#dashboard' # As a user I can access my dashboard

  resources :groups do # Full CRUD
    resources :events, only: [:new, :create] # As a user I can create an event for a certain group via a form
    resources :messages, only: [:create] # As a user I can send messages within the group page
    resources :group_memberships, only: [:new, :create] # As a user I can send invites to join the group
  end

  resources :events, only: [:index, :show, :edit, :update, :destroy] do # As a user I can do the rest of the crud inside the event page
    post 'votes', to: 'votes#bulk_create', as: 'votes'
    post 'full', to: 'events#full', as: 'full'
    post 'booked', to: 'events#booked', as: 'booked'
  end

  resources :event_memberships, only: [:update] # As a user I can declare that I won't be coming for this event

  resources :group_memberships, only: [:destroy] # As a user I can leave a group

  resources :notifications, only: [:index] # As a user I can see all my notifications

end

app/views/shared/_backto_links.erb
<% if @back_button == "group" %>
  <%= link_to group_path(@group) do %><i class="fas fa-users"></i><% end %>
<% elsif @back_button == "event" %>
  <%= link_to event_path(@event) do %><i class="fas fa-chevron-circle-left"></i><% end %>
<% elsif @back_button == "dashboard" %>
  <%= link_to dashboard_path do %><i class="fas fa-home"></i><% end %>
<% elsif @back_button == "back" %>
  <%= link_to :back do %><i class="fas fa-caret-left"></i><% end %>
<% elsif @back_button == "logout" %>
  <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-sign-out-alt"></i><% end %>
<% else %>
  <div></div>
<% end %>

app/views/shared/_bottombar.html.erb
<footer class="fixed-bottom w-100 border-top">
  <div class="container d-flex justify-content-between align-items-center px-4 py-3">
    <%= link_to events_path do %>
      <i class="fas fa-calendar-alt"></i>
    <% end %>

    <%= link_to groups_path do %>
      <i class="fas fa-users"></i>
    <% end %>

    <% if @show_bolt_button == true %>
      <div class="p-relative">
        <%= link_to new_group_event_path(@group), class: "bw_big-bolt-button d-flex justify-content-center align-items-center" do %>
          <i class="fas fa-bolt"></i>
        <% end %>
      </div>
    <% end %>

    <%= link_to notifications_path do %>
      <i class="fas fa-bell"></i>
    <% end %>

    <%= render 'shared/edit_links' %>
  </div>
</footer>

app/views/shared/_edit_links.erb
<% if @cog_button == "event" %>
  <%= link_to edit_event_path(@event) do %><i class="fas fa-cog"></i><% end %>
<% elsif @cog_button == "group" %>
  <%= link_to edit_group_path(@group) do %><i class="fas fa-users-cog"></i><% end %>
<% elsif @cog_button == "user" %>
  <%= link_to edit_user_registration_path(current_user) do %><i class="fas fa-user-cog"></i><% end %>
<% else %>
  <div></div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="sticky-top w-100 border-bottom">
  <div class="container d-flex justify-content-between align-items-center px-4 py-3">
    <%= render 'shared/backto_links' %>

    <h1><%= @page_title.length > 20 ? "#{@page_title[0..16]}..." : @page_title %></h1>
    
    <%= link_to edit_user_registration_path(current_user) do %>
    <div class="avatar">
      <%= show_svg(current_user.avatar_file) %>
    </div>
    <% end %>
  </div>
</nav>