config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get :dashboard, to: 'pages#dashboard' # As a user I can access my dashboard

  resources :groups do # Full CRUD
    resources :events, only: [:new, :create] # As a user I can create an event for a certain group via a form
    resources :messages, only: [:create] # As a user I can send messages within the group page
    resources :group_memberships, only: [:new, :create] # As a user I can send invites to join the group
  end

  resources :events, only: [:index, :show, :edit, :update, :destroy] do # As a user I can do the rest of the crud inside the event page
    post 'votes', to: 'votes#bulk_create', as: 'votes'
    post 'full', to: 'events#full', as: 'full'
    post 'booked', to: 'events#booked', as: 'booked'
  end

  resources :event_memberships, only: [:update] # As a user I can declare that I won't be coming for this event

  resources :group_memberships, only: [:destroy] # As a user I can leave a group

  resources :notifications, only: [:index] # As a user I can see all my notifications

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group


  has_many :event_memberships, dependent: :destroy
  has_many :event_places, dependent: :destroy

  has_many :users, through: :event_memberships
  has_many :votes, through: :event_memberships

  validates :title, presence: true
  validates :date, presence: true
  validates :city, presence: true

  after_create :invite_group_members

  def get_deadline_timestamp
    deadline = self.created_at + 48.hours
    deadline.to_i * 1000
  end

  private

  def invite_group_members
    # Get the users list
    users = self.group.users
    users.each do |user|
      # For each user in the list create an Event Membership with status true by default
      event_membership = EventMembership.create(user: user, event: self, status: true)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_group, only: [:new, :create]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event_id, only: [:full, :booked]
  # before_action :authenticate_user!

  def index
    yesterday = Date.today - 1
    @events = current_user.events.where("date > ?", yesterday).order(date: :asc)
  end

  def show
    # Set event users
    @users = @event.users
    # Set event group
    @group = @event.group
    # STAGE 1 (VOTE)
    if @event.stage == 1
      @event_membership = EventMembership.find_by(user_id: current_user, event_id: @event)
    # STAGE 2
    elsif @event.stage == 2
      # Set pending places
      set_event_places(@event)
      # Current place is the first pending event places
      set_event_place(@event_places)
      # Set random user
      @random_user = User.find(@event.random_user_id)
    # STAGE 3
    elsif @event.stage == 3
      # Final event place is the one that is booked
      @event_place = @event.event_places.find_by(booking_status: "booked")
    end
  end

  def new
    @event = Event.new
  end

  def create
    # New event with name, date, city and avatar_file
    @event = Event.new(event_params)
    # Assign the group to the new event
    @event.group = @group
    # Set the stage of the group to 1 (VOTES)
    @event.stage = 1
    # Try to save
    if @event.save
      # If save success all group members will be invited (after_create method) to the event
      # Send notifications
      Notification.new_event(@event)
      # And redirect to the event show
      redirect_to event_path(@event)
    else
      # If failure, log the event in the console
      p "- ERROR: Failed to create event:\n#{@event}."
      # And render the new form again
      render "new"
    end
  end

  def edit
    @group = @event.group
  end

  def update
    # Try to save
    if @event.update(event_params)
      # If save success redirect to event show
      redirect_to event_path(@event)
    else
      # If failure, log the event in the console
      p "- ERROR: Failed to update event:\n#{@event}."
      # And render the edit form again
      render "edit"
    end
  end

  def destroy
    # Store the group for further redirection
    @group = @event.group
    # Destroy the event
    @event.destroy
    # Redirect to the stored group show
    redirect_to group_path(@group)
  end

  def full
    # Set pending places
    set_event_places(@event)
    # Current place is the first pending event places
    set_event_place(@event_places)

    # Update booking status to full
    @event_place.booking_status = "full"

    # Save event place
    if @event_place.save
      # If save success redirect to event show
      redirect_to event_path(@event)
    else
      # If failure, log the event in the console
      p "- ERROR: Failed to update event:\n#{@event}."
      # And render the edit form again
      render "show"
    end
  end

  def booked
    # Set pending places
    set_event_places(@event)
    # Current place is the first pending event places
    set_event_place(@event_places)

    # Update booking status to booked
    @event_place.booking_status = "booked"
    # Update stage to 3
    @event.stage = 3

    # Save event AND event_place
    if @event.save && @event_place.save
      # Send notifications
      Notification.upstaged_to_3(@event, @event_place)
      # If save success redirect to event show
      redirect_to event_path(@event)
    else
      # If failure, log the event in the console
      p "- ERROR: Failed to update event:\n#{@event}."
      # And render the edit form again
      render "show"
    end
  end

  private

  # Find event by id in DB
  def set_event
    @event = Event.find(params[:id])
  end

  # Find event by event_id in DB
  def set_event_id
    @event = Event.find(params[:event_id])
  end

  # Find group by group_id in DB
  def set_group
    @group = Group.find(params[:group_id])
  end

  # Whitelist params
  def event_params
    params.require(:event).permit(:title, :date, :city, :avatar_file)
  end

  # Set the pending places
  def set_event_places(event)
    @event_places = event.event_places.where(booking_status: "pending")
  end

  # Set current event place
  def set_event_place(event_places)
    @event_place = event_places[0]
  end
end

app/views/events/_editform.html.erb
<%= simple_form_for [ @event ] do |f| %>
  <div class="d-flex flex-column form-inputs my-3 bw_form-inputs-no-border justify-content-center text-center">
    <%= f.input :title, label:'Event name :', placeholder: 'Type in the event name',
                required: true,
                autofocus: true %>
    <%= f.input :date, label:'Event date :',
                required: true,
                autofocus: true %>
    <%= f.input :city, label:'Event city :', placeholder: 'Type in the name of the city',
                required: true,
                autofocus: true %>
    <%= f.input :avatar_file, :as => :hidden,
                required: true, input_html: { id: 'avatar' } %>

    <label class="string required">Choose your avatar: *</label>
    <div class="mt-3 avatars-container row row-cols-3">
      <% @avatars = Avatar.get_event_avatars %>
        <% @avatars.each do |avatar| %>
          <div class="avatars col" data-avatar=<%="avatars/events/#{avatar}.svg"%>>
            <%= show_svg("avatars/events/#{avatar}.svg") %>
          </div>
        <% end %>
    </div>

    <%= f.button :submit, class: 'btn btn-primary w-100 fixed-bottom btn-lg rounded-0' %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for [ @group, @event ] do |f| %>
  <div class="d-flex flex-column form-inputs my-3 bw_form-inputs-no-border justify-content-center text-center">
    <%= f.input :title, label:'Event name :', placeholder: 'Type in the event name',
                required: true,
                autofocus: true %>
    <%= f.input :date, label:'Event date :',
                required: true,
                autofocus: true %>
    <%= f.input :city, label:'Event city :', placeholder: 'Type in the name of the city',
                required: true,
                autofocus: true %>
    <%= f.input :avatar_file, :as => :hidden,
                required: true, input_html: { id: 'avatar' } %>

    <label class="string required">Choose your avatar: *</label>
    <div class="mt-3 avatars-container row row-cols-3">
      <% @avatars = Avatar.get_event_avatars %>
        <% @avatars.each do |avatar| %>
          <div class="avatars col" data-avatar=<%="avatars/events/#{avatar}.svg"%>>
            <%= show_svg("avatars/events/#{avatar}.svg") %>
          </div>
        <% end %>
    </div>

    <%= f.button :submit, class: 'btn btn-primary w-100 fixed-bottom btn-lg rounded-0' %>
  </div>
<% end %>

app/views/events/_show_stage1.html.erb
<div class="container d-flex flex-column justify-content-between bw_padding-bottom-2 mt-4">
<h2 class="text-center body-font h-32px font-bolder">Give your choice!</h2>
<div class="d-flex justify-content-center align-items-center bw_countdown">
  <div id="clockdiv" data-deadline="<%= @event.get_deadline_timestamp %>">
    <div class="d-inline-flex">
      <span class="days"></span>
      <div class="smalltext">:</div>
    </div>
    <div class="d-inline-flex">
      <span class="hours"></span>
      <div class="smalltext">:</div>
    </div>
    <div class="d-inline-flex">
      <span class="minutes"></span>
      <div class="smalltext">:</div>
    </div>
    <div class="d-inline-flex">
      <span class="seconds"></span>
      <div class="smalltext"></div>
    </div>
  </div>
</div>

  <strong class="text-center mb-4">Vote by clicking on the faces.</strong>

  <%= form_tag event_votes_path(@event), method: :post do |f| %>

    <% Vote::VOTE_TASTES.each do |taste| %>

      <div class="d-flex justify-content-between align-items-center py-3 bw_event-vote">

        <div class="d-flex align-items-center">
          <div class="avatars mb-0">
            <%= show_svg("avatars/tastes/#{taste.downcase}.svg") %>
          </div>
          <span class="body-font"><%= taste %></span>
        </div>

        <div>
          <% taste_formatted = taste.gsub(" ", "_") %>
          <div class="d-flex justify-content-center align-items-center bw_event-likes-container">
            <input type="text" name="tastes[<%= taste_formatted %>]" value="0" id="<%= taste_formatted %>_like" hidden>

            <div class="bw_event-likes <%= taste_formatted %>" data-taste="<%= taste_formatted %>" data-tastelike="-100">
              <i class="far fa-angry"></i>
            </div>
            <div class="bw_event-likes active <%= taste_formatted %>" data-taste="<%= taste_formatted %>" data-tastelike="0">
              <i class="far fa-meh"></i>
            </div>
            <div class="bw_event-likes <%= taste_formatted %>" data-taste="<%= taste_formatted %>" data-tastelike="1">
              <i class="far fa-grin-hearts"></i>
            </div>
          </div>
        </div>

      </div>

    <% end %>
    <input type="submit" value="Confirm" class="btn btn-primary w-100 fixed-bottom btn-lg rounded-0 bw_margin-bottom-1">

  <% end %>

</div>

app/views/events/_show_stage2-others.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center mt-4 bw_padding-bottom-2 bw_disabled">
  <%= image_tag @random_user.avatar_file, class: "bw_event-random-user bw_image-round my-4" %>
  <h2 class="body-font text-center font-bolder"><span class="text-primary"><%= @random_user.nickname %></span> has to book it!</h2>
  <div class="bw_big-event-infos d-flex flex-row justify-content-between align-items-center mt-2">
    <strong><i class="fas fa-calendar-check mr-2 text-primary"></i> <%= @event.date.strftime("%b %d") %></strong>
    <strong><i class="fas fa-users mr-2 text-primary"></i> <%= @event.users.count %></strong>
  </div>

  <%= image_tag @event_place.yelp_image_url, class: "bw_event-cover bw_image-round my-4" %>

  <% if !@event_place.yelp_rating.nil? %><p class="bw_stars"><% @event_place.yelp_rating.times do %> <i class="fas fa-star"></i> <% end %> (<%= @event_place.yelp_review_count %>)</p><% end %>
</div>

app/views/events/_show_stage2-random.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center mt-4 bw_padding-bottom-2">
  <strong class="text-muted">You have to book:</strong>
  <div class="bw_big-event-infos d-flex flex-row justify-content-between align-items-center mt-2">
    <strong><i class="fas fa-calendar-check mr-2 text-primary"></i> <%= @event.date.strftime("%b %d") %></strong>
    <strong><i class="fas fa-users mr-2 text-primary"></i> <%= @event.users.count %></strong>
  </div>

  <%= image_tag @event_place.yelp_image_url, class: "bw_event-cover bw_image-round my-4" %>

  <h2 class="h-32px text-center"><%= @event_place.yelp_name %></h2>

  <% if !@event_place.yelp_rating.nil? %><p class="bw_stars"><% @event_place.yelp_rating.times do %> <i class="fas fa-star text-primary"></i> <% end %> (<%= @event_place.yelp_review_count %>)</p><% end %>
  
  <p><i class="fas fa-map-marker-alt mr-2 text-primary"></i><%= @event_place.yelp_address1 %></p>
  <p><%= @event_place.yelp_zip_code %>, <%= @event_place.yelp_city %></p>

  <div class="bw_big-links d-flex flex-row justify-content-between align-items-center">
    <%= link_to "tel:#{@event_place.yelp_phone}" do %><i class="fas fa-phone"></i><% end %>
    <%= link_to "https://www.yelp.com/map/#{@event_place.yelp_alias}" do %><i class="fas fa-location-arrow"></i><% end %>
    <%= link_to @event_place.yelp_url do %><i class="fab fa-yelp"></i><% end %>
  </div>

</div>

<div class="row row-cols-2 w-100 fixed-bottom bw_margin-bottom-1 mx-0">
  <%= link_to event_full_path(@event), class: "btn btn-dark w-100 btn-lg rounded-0", method: :post do %><i class="fas fa-thumbs-down"></i><% end %>
  <%= link_to event_booked_path(@event), class: "btn btn-primary w-100 btn-lg rounded-0", method: :post do %><i class="fas fa-thumbs-up"></i><% end %>
</div>

app/views/events/_show_stage3.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center mt-4 bw_padding-bottom-2">
  <strong class="text-muted">You are going to:</strong>
  <div class="bw_big-event-infos d-flex flex-row justify-content-between align-items-center mt-2">
    <strong><i class="fas fa-calendar-check mr-2 text-primary"></i> <%= @event.date.strftime("%b %d") %></strong>
    <strong><i class="fas fa-users mr-2 text-primary"></i> <%= @event.users.count %></strong>
  </div>

  <%= image_tag @event_place.yelp_image_url, class: "bw_event-cover bw_image-round my-4" %>

  <h2 class="h-32px text-center"><%= @event_place.yelp_name %></h2>

  <% if !@event_place.yelp_rating.nil? %><p class="bw_stars"><% @event_place.yelp_rating.times do %> <i class="fas fa-star text-primary"></i> <% end %> (<%= @event_place.yelp_review_count %>)</p><% end %>
  
  <p><i class="fas fa-map-marker-alt mr-2 text-primary"></i><%= @event_place.yelp_address1 %></p>
  <p><%= @event_place.yelp_zip_code %>, <%= @event_place.yelp_city %></p>

  <div class="bw_big-links d-flex flex-row justify-content-between align-items-center">
    <%= link_to "tel:#{@event_place.yelp_phone}" do %><i class="fas fa-phone"></i><% end %>
    <%= link_to "https://www.yelp.com/map/#{@event_place.yelp_alias}" do %><i class="fas fa-location-arrow"></i><% end %>
    <%= link_to @event_place.yelp_url do %><i class="fab fa-yelp"></i><% end %>
  </div>

</div>

app/views/events/_show_waiting.html.erb
<div class="d-flex flex-column bw_h-100-vh justify-content-center align-items-center">
  <h2 class="text-center bw_big-word px-3 mb-5"> Your vote has been submitted !</h2>

  <strong class="h-32px"><%= @event.votes.group_by(&:event_membership_id).count %> / <%= @event.event_memberships.count %> <i class="fas fa-user-friends"></i></strong>
</div>

app/views/events/edit.html.erb
<% @page_title = @event.title %>
<% @back_button = "back" %>
<% @show_bolt_button = true %>

<%= render 'shared/navbar' %>
<div class="container col-10 col-lg-4 d-flex flex-column justify-content-center my-5">
  <%= render 'editform' %>
</div>

app/views/events/index.html.erb
<% @page_title = "Events" %>
<% @back_button = "logout" %>
<% @cog_button = "user" %>

<%= render "shared/navbar"  %>


<div class="container d-flex flex-column justify-content-center mt-4 bw_padding-bottom-1">
  <% if !@events.where(stage: 3).empty? %>
    <div class="mb-5">
      <h2>Upcoming events</h2>
      <% @events.where(stage: 3).each do |event| %>

        <div class="bw_event d-flex flex-row justify-content-left align-items-center py-3 px-0 pr-3">
          <div class="col-2 pl-0">
            <%= show_svg(event.avatar_file) %>
          </div>
          <div class="flex-grow-1 justify-content-between d-flex flex-row align-items-center">
            <strong class="text-dark"><%= link_to "#{event.title}", event_path(event) %></strong>
            <small class="text-muted"><%= event.date.strftime("%a %b %d") %></small>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>


  <% if !@events.where(stage: 2).empty? %>
    <div class="mb-5">
      <h2>Booking in process...</h2>
      <% @events.where(stage: 2).each do |event| %>

        <div class="bw_event d-flex flex-row justify-content-left align-items-center py-3 px-0 pr-3">
          <div class="col-2 pl-0">
            <%= show_svg(event.avatar_file) %>
          </div>
          <div class="flex-grow-1 justify-content-between d-flex flex-row align-items-center">
            <strong class="text-dark"><%= link_to "#{event.title}", event_path(event) %></strong>
            <small class="text-muted"><%= event.date.strftime("%a %b %d") %></small>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if !@events.where(stage: 1).empty? %>
    <div class="mb-5">
      <h2>Votes in process...</h2>
      <% @events.where(stage: 1).each do |event| %>

        <div class="bw_event d-flex flex-row justify-content-left align-items-center py-3 px-0 pr-3">
          <div class="col-2 pl-0">
            <%= show_svg(event.avatar_file) %>
          </div>
          <div class="flex-grow-1 justify-content-between d-flex flex-row align-items-center">
            <strong class="text-dark"><%= link_to "#{event.title}", event_path(event) %></strong>
            <small class="text-muted"><%= event.date.strftime("%a %b %d") %></small>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= render "shared/bottombar"%>

app/views/events/new.html.erb
<% @page_title = "New event" %>
<% @back_button = "back" %>
<% @cog_button = "group" %>
<% @show_bolt_button = true %>

<%= render 'shared/navbar' %>
<div class="container col-10 col-lg-4 d-flex flex-column justify-content-center my-5">
  <h2 class="text-center">For: <%= @group.title %></h2>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<% @page_title = "#{@event.title}" %>
<% @back_button = "back" %>
<% @cog_button = "event" %>
<% @show_bolt_button = true %>
<%= render 'shared/navbar' %>


<div class="container d-flex flex-column justify-content-between">
</div>

<% if @event.stage == 1 && current_user.has_voted?(@event) %>
    <%= render 'show_waiting' %>

  <% elsif @event.stage == 1 %>
    <%= render 'show_stage1' %>

  <% elsif @event.stage == 2 && current_user == @random_user %>
    <%= render 'show_stage2-random' %>

  <% elsif @event.stage == 2 %>
    <%= render 'show_stage2-others' %>

  <% elsif @event.stage == 3 %>
    <%= render 'show_stage3' %>

<% end %>

<%= render 'shared/bottombar' %>